export { default as Hero } from './Hero'
export { default as Navbar} from './Navbar'
export { default as Games} from './Games'
export { default as Details } from '../Pages/Details'
export {default as Main} from '../Pages/Main'
export { default as Register } from './Register'
export { default as Login } from './Login'